### PR TITLE
fixed small error in comment

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Comment by KFlash** [comment]
Good catch! This is copied from the file [`src/seafox.ts`](https://github.com/KFlash/seafox/blob/master/src/seafox.ts#L16) Could you correct the same in that file?

**Comment by 0xflotus** [comment]
> Good catch! This is copied from the file [`src/seafox.ts`](https://github.com/KFlash/seafox/blob/master/src/seafox.ts#L16) Could you correct the same in that file?

Of course.

**Comment by KFlash** [comment]
Thanks! I will merge this soon as the checks are done

**Comment by KFlash** [comment]
@0xflotus Do you want a challenge? I have 2 non-failing cases for nullish. Could you make them fail as expected? I need to focus on some optimization tweaks

**Comment by 0xflotus** [comment]
> @0xflotus Do you want a challenge? I have 2 non-failing cases for nullish. Could you make them fail as expected? I need to focus on some optimization tweaks

Please show me the cases and I will try. :)

**Comment by KFlash** [comment]
The tests [is here](https://github.com/KFlash/seafox/blob/master/test/parser/expressions/nullish.ts#L21-L22) and the code [is here](https://github.com/KFlash/seafox/blob/master/src/parser/expressions.ts#L203)

The issue is that the token past as argument isn't validated correctly. Coalece have precedence 1 and the others are either 2 or 3.

**Pull request merged**
